SERVER_NAME: Open RSC
PREFIX: @gre@OpenRSC:@whi@
LOGGING: true
MAX_PLAYERS: 1000
COMMAND_PREFIX: ::

SERVER_VERSION: 7
SERVER_IP: 0.0.0.0
SERVER_PORT: 53595
WEB_PORT: 53594
MAX_LOGINS_PER_IP: 5

# Database connection:
DB_HOST: localhost
DB_NAME: openrsc
DB_LOGIN: root
DB_PASS: root
CONFIG_DB_NAME: openrsc_config
LOG_DB_NAME: openrsc_logs
TOOLS_DB_NAME: openrsc_tools

# XP rates:
COMBAT_XP_RATE: 1
SKILL_XP_RATE: 1
WILD_XP_BONUS: 1
SKULLED_XP_BONUS: 1

# Miscellaneous:
ALLOW_WEAKENS: true
ALLOW_GODSPELLS: true
# The number of milliseconds of heads-up notice that the clients receive before a shutdown:
SHUTDOWN_TIME_MILLIS: 60000
AVATAR_DIR: avatars/

# Sleeping related:
DISABLE_FATIGUE: false
DISABLE_SLEEP_WORDS: true
BAN_FAILED_SLEEP: false

# Custom feature:
DISABLE_RUNECRAFTING: true
# The amount to multiply the generated runes by:
RUNECRAFTING_AMOUNT_MULTIPLIER: 1
